/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author WS
 */
import java.awt.Color;
import java.io.IOException;
import java.io.FileWriter;
import java.io.BufferedWriter;

public class RegistrationFrm extends javax.swing.JFrame {

    String username, pass1, pass2, firstname,lastname;

    /**
     * Creates new form RegistrationFrm
     */
    public RegistrationFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpspec = new javax.swing.ButtonGroup();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtaddrss = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pss1 = new javax.swing.JPasswordField();
        pss2 = new javax.swing.JPasswordField();
        cmbsex = new javax.swing.JComboBox<>();
        chkshow = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        chkProgram = new javax.swing.JCheckBox();
        chkVG = new javax.swing.JCheckBox();
        chkTL = new javax.swing.JCheckBox();
        chkUD = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        rbtnJava = new javax.swing.JRadioButton();
        rbtnPython = new javax.swing.JRadioButton();
        btnsubmit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(102, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRATION FORM");

        jLabel2.setBackground(new java.awt.Color(102, 255, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Username");

        txtusername.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtusername.setForeground(new java.awt.Color(153, 153, 153));
        txtusername.setText(" username");
        txtusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(102, 255, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setBackground(new java.awt.Color(102, 255, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Confirm Password");

        jLabel5.setBackground(new java.awt.Color(102, 255, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("First name:");

        txtfirstname.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtfirstname.setForeground(new java.awt.Color(153, 153, 153));
        txtfirstname.setText(" firstname");
        txtfirstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtfirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfirstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfirstnameFocusLost(evt);
            }
        });
        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(102, 255, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Lastname:");

        txtlastname.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtlastname.setForeground(new java.awt.Color(153, 153, 153));
        txtlastname.setText(" lastname");
        txtlastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtlastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlastnameFocusLost(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(102, 255, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Address:");

        txtaddrss.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtaddrss.setForeground(new java.awt.Color(153, 153, 153));
        txtaddrss.setText(" address");
        txtaddrss.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtaddrss.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtaddrss.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtaddrssFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtaddrssFocusLost(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(102, 255, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Sex:");

        pss1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pss1.setForeground(new java.awt.Color(153, 153, 153));
        pss1.setText(" Password");
        pss1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pss1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pss1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pss1FocusLost(evt);
            }
        });
        pss1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pss1ActionPerformed(evt);
            }
        });

        pss2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pss2.setForeground(new java.awt.Color(153, 153, 153));
        pss2.setText(" Password");
        pss2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pss2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pss2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pss2FocusLost(evt);
            }
        });

        cmbsex.setBackground(new java.awt.Color(204, 204, 204));
        cmbsex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others", " ", " " }));
        cmbsex.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbsex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsexActionPerformed(evt);
            }
        });

        chkshow.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        chkshow.setForeground(new java.awt.Color(51, 51, 51));
        chkshow.setText("show");
        chkshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkshowActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(102, 255, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Skills:");

        chkProgram.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkProgram.setText("Programming");
        chkProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProgramActionPerformed(evt);
            }
        });

        chkVG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkVG.setText("Visual Graphics");
        chkVG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVGActionPerformed(evt);
            }
        });

        chkTL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkTL.setText("Team Lead");
        chkTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTLActionPerformed(evt);
            }
        });

        chkUD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkUD.setText("UI/UX Design");
        chkUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUDActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(102, 255, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Specialization:");

        btngrpspec.add(rbtnJava);
        rbtnJava.setText("Java");
        rbtnJava.setToolTipText("");

        btngrpspec.add(rbtnPython);
        rbtnPython.setText("Python");

        btnsubmit.setBackground(new java.awt.Color(51, 102, 255));
        btnsubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        jLabel11.setText("Already have an account?");

        lblLogin.setForeground(new java.awt.Color(51, 51, 51));
        lblLogin.setText("Log in");
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });

        lbl1.setForeground(new java.awt.Color(255, 0, 0));
        lbl1.setText("*");

        lbl2.setForeground(new java.awt.Color(255, 0, 0));
        lbl2.setText("*");

        lbl4.setForeground(new java.awt.Color(255, 0, 0));
        lbl4.setText("*");

        lbl3.setForeground(new java.awt.Color(255, 0, 0));
        lbl3.setText("*");

        lbl5.setForeground(new java.awt.Color(255, 0, 0));
        lbl5.setText("*");

        lbl6.setForeground(new java.awt.Color(255, 0, 0));
        lbl6.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pss2)
                                                    .addComponent(txtfirstname)
                                                    .addComponent(txtlastname)
                                                    .addComponent(txtaddrss)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(pss1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(20, 20, 20))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cmbsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(141, 141, 141)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                        .addComponent(chkshow))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chkProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(chkTL)
                                                    .addComponent(rbtnJava))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbtnPython)
                                                    .addComponent(chkUD)
                                                    .addComponent(chkVG))))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogin)
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbl1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl2)
                            .addComponent(chkshow, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(pss1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pss2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lbl3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtaddrss, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cmbsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkProgram)
                    .addComponent(chkVG)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTL)
                    .addComponent(chkUD))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rbtnJava)
                    .addComponent(rbtnPython))
                .addGap(18, 18, 18)
                .addComponent(btnsubmit)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(jLabel11))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        // TODO add your handling code here:
        Login form = new Login();
        form.show();
        this.hide();
    }//GEN-LAST:event_lblLoginMouseClicked

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        String username = txtusername.getText();
        String pass1 = pss1.getText();
        String pass2 = pss2.getText();
        String firstname = txtfirstname.getText();
        String lastname = txtlastname.getText();
        String addrss = txtaddrss.getText();


        if (username.isEmpty() || pass1.isEmpty() || pass2.isEmpty() || firstname.isEmpty()|| lastname.isEmpty() || addrss.isEmpty()) {
            txtusername.setBackground(Color.RED);
            pss1.setBackground(Color.RED);
            pss2.setBackground(Color.RED);
            txtfirstname.setBackground(Color.RED);
            txtlastname.setBackground(Color.RED);
            txtaddrss.setBackground(Color.RED);
            System.out.println("Please fill in all fields.");
            return;
        } 
         if (!pass1.equals(pass2)) {
        
        pss2.setBackground(Color.RED); 
        System.out.println("Passwords do not match. Please try again.");
        return;
    }
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(username + ".txt"))) {
            writer.write(username);
            writer.newLine();
            writer.write(pass1);
            writer.newLine();
            writer.write(pass2);
            writer.newLine();
            writer.write(firstname);
            writer.newLine();
            writer.write(lastname);
            writer.newLine();
            writer.write(addrss);
            writer.newLine();

            if (chkProgram.isSelected()) {
                writer.write(chkProgram.getText() + "\n");
            }
            if (chkTL.isSelected()) {
                writer.write(chkTL.getText() + "\n");
            }
            if (chkUD.isSelected()) {
                writer.write(chkUD.getText() + "\n");
            }
            if (chkVG.isSelected()) {
                writer.write(chkVG.getText() + "\n");
            }
            String btngrpspec = "";
            if (rbtnJava.isSelected()) {
            btngrpspec = "rbtnJava";
            } else if (rbtnPython.isSelected()) {
            btngrpspec = "rbtnPython";
            } else {
            System.out.println("Please select a Specialization.");
            return;
            }
            writer.write((String) cmbsex.getSelectedItem());
            writer.close();
            System.out.println("Data has been successfully saved to the file.");
 
        } catch (IOException e) {
            e.printStackTrace();
        }
        Login loginform = new Login();
        loginform.show();
        this.hide();
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void chkUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkUDActionPerformed

    private void chkTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTLActionPerformed

    private void chkVGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkVGActionPerformed

    private void chkProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkProgramActionPerformed

    private void chkshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkshowActionPerformed
        // TODO add your handling code here:
        if(chkshow.isSelected()){
            pss1.setEchoChar((char)0);
            pss2.setEchoChar((char)0);

        }else{
            pss1.setEchoChar('*');
            pss2.setEchoChar('*');

        }
    }//GEN-LAST:event_chkshowActionPerformed

    private void cmbsexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbsexActionPerformed

    private void pss2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pss2FocusLost
        String ps2 = pss2.getText();
        if(ps2.isEmpty()){
            pss2.setText("confirmpassword");
            pss2.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_pss2FocusLost

    private void pss2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pss2FocusGained
        pss2.setBackground(Color.WHITE);
        pss2.setText("");
        pss2.setForeground(Color.BLACK);
    }//GEN-LAST:event_pss2FocusGained

    private void pss1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pss1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pss1ActionPerformed

    private void pss1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pss1FocusLost
        String ps1 = pss1.getText();
        if(ps1.isEmpty()){
            pss1.setText("password");
            pss1.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_pss1FocusLost

    private void pss1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pss1FocusGained
        pss1.setBackground(Color.WHITE);
        pss1.setText("");
        pss1.setForeground(Color.BLACK);
    }//GEN-LAST:event_pss1FocusGained

    private void txtaddrssFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaddrssFocusLost
        String add = txtaddrss.getText();
        if(add.isEmpty()){
            txtaddrss.setText("address");
            txtaddrss.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtaddrssFocusLost

    private void txtaddrssFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaddrssFocusGained
        txtaddrss.setBackground(Color.WHITE);
        txtaddrss.setText("");
        txtaddrss.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtaddrssFocusGained

    private void txtlastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlastnameFocusLost
        String lname = txtlastname.getText();
        if(lname.isEmpty()){
            txtlastname.setText("lastname");
            txtlastname.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtlastnameFocusLost

    private void txtlastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlastnameFocusGained
        txtlastname.setBackground(Color.WHITE);
        txtlastname.setText("");
        txtlastname.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtlastnameFocusGained

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void txtfirstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstnameFocusLost
        String fname = txtfirstname.getText();
        if(fname.isEmpty()){
            txtfirstname.setText("firstname");
            txtfirstname.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtfirstnameFocusLost

    private void txtfirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstnameFocusGained
        txtfirstname.setBackground(Color.WHITE);
        txtfirstname.setText("");
        txtfirstname.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtfirstnameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        String user = txtusername.getText();
        if(user.isEmpty()){
            txtusername.setText("username");
            txtusername.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        txtusername.setBackground(Color.WHITE);
        txtusername.setText("");
        txtusername.setForeground(Color.BLACK);

    }//GEN-LAST:event_txtusernameFocusGained

    private void lbl1ActionPerformed(java.awt.event.ActionEvent evt){
          String user = txtusername.getText();
          
          if(user.isEmpty()){
              lbl1.setText("");
          }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrpspec;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JCheckBox chkProgram;
    private javax.swing.JCheckBox chkTL;
    private javax.swing.JCheckBox chkUD;
    private javax.swing.JCheckBox chkVG;
    private javax.swing.JCheckBox chkshow;
    private javax.swing.JComboBox<String> cmbsex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPasswordField pss1;
    private javax.swing.JPasswordField pss2;
    private javax.swing.JRadioButton rbtnJava;
    private javax.swing.JRadioButton rbtnPython;
    private javax.swing.JTextField txtaddrss;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
